### ISSUE TITLE
Modify token ratio loss

### ISSUE THREAD

**Issue by King4819** [uzh-rpg/svit#9]
Hi, in your work you utilize **dynamic** pruning ratio loss (**averaged across all tokens and across images in a batch, resulting in more tokens allocated for complex images and fewer tokens for simpler images**), which implements the below equation:

![image](https://github.com/uzh-rpg/svit/assets/120317730/47d60c15-2846-4226-824e-b844aa3de00b)

I would like to ask that how to modify the token ratio loss to **fixed** (**does not average token usage across images within a batch, thereby penalizing each image towards the same keeping ratio**) as most pruning methods (e.g., DynamicViT)

![image](https://github.com/uzh-rpg/svit/assets/120317730/d0d9800e-6525-4c2f-8dda-47e9f5c8de56)

Thanks a lot. This is such an awesome work !!!

**Comment by kaikai23** [comment]
Hi, it is defined here: https://github.com/uzh-rpg/svit/blob/master/mmdet_custom/models/backbones/adapter_modules.py#L436-L441

**Comment by King4819** [comment]
@kaikai23 Thanks for your reply. If I change the arg self.ratio_per_sample to **False** (default True), it will perform fixed token ratio loss (does not average token usage across images within a batch, thereby penalizing each image towards the same keeping ratio) ?

**Comment by kaikai23** [comment]
self.ratio_per_sample=False corresponds to dynamic ratio loss, and Ture correpsondes to fixed ratio loss.
I think we used dynamic ratio loss by default? https://github.com/uzh-rpg/svit/blob/d2472c13e667f4ef4c098898faec2e6cbe6c8e01/mmdet_custom/models/backbones/base/selective_vit.py#L100

**Comment by King4819** [comment]
Oh I get it. Thanks for your reply
